<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <RimWorldPath Condition="'$(RimWorldPath)' == '' and '$(RIMWORLD_PATH)' != ''">$(RIMWORLD_PATH)</RimWorldPath>
    <RimWorldPath Condition="'$(RimWorldPath)' == '' and $([MSBuild]::IsOSPlatform('Windows'))">C:/Program Files (x86)/Steam/steamapps/common/RimWorld</RimWorldPath>
    <RimWorldPath Condition="'$(RimWorldPath)' == '' and $([MSBuild]::IsOSPlatform('Linux'))">$(HOME)/.steam/steam/steamapps/common/RimWorld</RimWorldPath>
    <RimWorldPath Condition="'$(RimWorldPath)' == '' and $([MSBuild]::IsOSPlatform('OSX'))">$(HOME)/Library/Application Support/Steam/steamapps/common/RimWorld</RimWorldPath>
    <RimWorldDataDir Condition="'$(RimWorldDataDir)' == '' and $([MSBuild]::IsOSPlatform('Windows'))">RimWorldWin64_Data</RimWorldDataDir>
    <RimWorldDataDir Condition="'$(RimWorldDataDir)' == '' and $([MSBuild]::IsOSPlatform('Linux'))">RimWorldLinux_Data</RimWorldDataDir>
    <RimWorldDataDir Condition="'$(RimWorldDataDir)' == '' and $([MSBuild]::IsOSPlatform('OSX'))">RimWorldMac.app/Contents/Resources/Data</RimWorldDataDir>
    <RimWorldManaged>$(RimWorldPath)/$(RimWorldDataDir)/Managed</RimWorldManaged>
  </PropertyGroup>
</Project>
